- id: doi.org/10.1016/j.envpol.2023.121419
  type: paper
  description: Reintroducing a keystone bioturbator can facilitate microbial bioremediation in urban polluted sediments
  date: 2023-1-5
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0269749123004219-ga1.jpg
  tags:
    - open science
    - Microbial remediation
    - Urban ecology

- id: https://doi.org/10.21203/rs.3.rs-3012963/v1
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
